name: Create Tag and Release

on:
  push:
    branches:
      - '*'

jobs:
  tag-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create tag and release
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_GIT }}
        run: |
          BRANCH=$(echo "${GITHUB_REF#refs/heads/}")
          TAG=$(echo "${BRANCH//\//_}")
          git tag $TAG
          git push --tags
          curl --request POST \
            --url https://api.github.com/repos/$GITHUB_REPOSITORY/releases \
            --header "authorization: Bearer $GITHUB_TOKEN" \
            --header 'content-type: application/json' \
            --data '{
              "tag_name": "'"$TAG"'",
              "target_commitish": "'"$BRANCH"'",
              "name": "'"$TAG"'",
              "body": "Release for branch '"$BRANCH"'",
              "draft": false,
              "prerelease": false
            }'
