---
applications:
- name: dev-api-security
  instances: 1
  memory: 512M
  path: api/CcsSso.Security.Api/bin/Debug/net5.0
  buildpack: https://github.com/cloudfoundry/dotnet-core-buildpack.git
  routes:
    - route: dev-api-security.london.cloudapps.digital
  services:
    - dev-security-pg-service
    - dev-vault    
  env:
    CACHE_NUGET_PACKAGES: false