---
applications:
- name: ccs-sso-api
  instances: 1
  memory: 512M
  path: api/SecurityApi/CcsSso.Security.Api/bin/Debug/net5.0
  buildpack: https://github.com/cloudfoundry/dotnet-core-buildpack.git
  random-route: true
  env:
    CACHE_NUGET_PACKAGES: false