name: Create Tag and Release

on:
  push:
    branches:
      - '*'

jobs:
  tag-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create tag and release
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_GIT }}
        run: |
          # set version range
          START_VERSION=1.0.0
          END_VERSION=1.0.5

          # loop through versions and create releases
          for ((i=$(echo $START_VERSION | tr '.' ' ');i<=$(echo $END_VERSION | tr '.' ' ');i++)); do
            VERSION=$(echo $i | tr ' ' '.')
            TAG="v$VERSION"
            RELEASE_NAME="Release $VERSION"
            RELEASE_BODY="Release for version $VERSION"
            # create release via GitHub API
            curl --request POST \
                      --url https://api.github.com/repos/$GITHUB_REPOSITORY/releases \
                      --header "authorization: Bearer $GITHUB_TOKEN" \
                      --header 'content-type: application/json' \
                      --data '{
                        "tag_name": "'"$TAG"'",
                        "target_commitish": "'"$BRANCH"'",
                        "name": "'"$TAG"'",
                        "body": "Release for branch '"$BRANCH"'",
                        "draft": false,
                        "prerelease": false
                      }'
          done

