name: Trufflehog PR Scan

permissions:
  contents: read
  id-token: write
  issues: write
  pull-requests: write

on:
  pull_request:
    branches:
      - "${{ github.event.repository.default_branch }}"

jobs:
  trufflehog-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Install Trufflehog
        run: |
          pip3 install trufflehog

      - name: Run Trufflehog Scan
        id: trufflehog
        run: |
          trufflehog ${{ github.repository }} --regex --entropy=TRUE

      - name: Scan Results Status
        if: steps.trufflehog.outcome == 'failure'
        run: exit 1
